DROP TABLE UTILISATEURS CASCADE CONSTRAINTS purge;
DROP TABLE APPARTEMENTS CASCADE CONSTRAINTS purge;
DROP SEQUENCE NUMERO_APPART;

CREATE TABLE UTILISATEURS (	
	Nom VARCHAR2(40) NOT NULL,
	Login VARCHAR2(20),
	Mdp VARCHAR2(40) NOT NULL,
	Profil VARCHAR2(40) NOT NULL,
	CONSTRAINT PK_UTILISATEURS PRIMARY KEY (Login),
	CONSTRAINT CHK_PROFILE CHECK (Profil IN ('PROPRIETAIRE', 'AGENTIMMO'))
);

CREATE TABLE APPARTEMENTS (
	Numero INTEGER, 
	TypeAppart VARCHAR2(6),
	Adresse VARCHAR2(75), 
	MontantVente NUMBER (10,2),
	DatePublication Date,
	DateValidation Date,
	AgentValidateur VARCHAR2(20),
	LoginProp VARCHAR2(20),
	CONSTRAINT PK_APPARTEMENT PRIMARY KEY (Numero),
	CONSTRAINT FK_PROP_APPART FOREIGN KEY (LoginProp) REFERENCES UTILISATEURS (Login),
	CONSTRAINT FK_VALID_APPART FOREIGN KEY (AgentValidateur) REFERENCES UTILISATEURS (Login)
);

CREATE SEQUENCE NUMERO_APPART START WITH 0 MINVALUE 0 INCREMENT BY 1;

INSERT INTO UTILISATEURS VALUES ('Paul', 'paul@','paul', 'AGENTIMMO');
INSERT INTO UTILISATEURS VALUES ('Anne', 'anne@','anne', 'AGENTIMMO');

COMMIT;