CREATE TABLE APPARTEMENTS (
	Numero INTEGER, 
	TypeAppart VARCHAR(6),
	Adresse VARCHAR(75), 
	MontantVente FLOAT (10,2),
	DatePublication Date,
	DateValidation Date,
	AgentValidateur VARCHAR(20),
	LoginProp VARCHAR(20),
	CONSTRAINT PK_APPARTEMENT PRIMARY KEY (Numero),
	CONSTRAINT FK_PROP_APPART FOREIGN KEY (LoginProp) REFERENCES UTILISATEURS (Login),
	CONSTRAINT FK_VALID_APPART FOREIGN KEY (AgentValidateur) REFERENCES UTILISATEURS (Login)
);

INSERT INTO UTILISATEURS VALUES ('Paul', 'paul@','paul', 'AGENTIMMO');
INSERT INTO UTILISATEURS VALUES ('Anne', 'anne@','anne', 'AGENTIMMO');